#!/usr/bin/env bash

for i in *.md ; do
    pandoc -r markdown_github -s -S --latex-engine=pdflatex  $i -o $i.pdf
    pandoc -r markdown_github -s -S $i -o $i.html
    pandoc -r markdown_github -s -S $i -o $i.odt
done
